### PR TITLE
Update ROCm and GCC compilers for frontier to more recent versions

### PR DESCRIPTION
**Pull request by kmorel**

### CODE REVIEW

**Comment by kmorel** [comment]
@kwryankrattiger To compile the latest version of ParaView (or more specifically, the LLVM module it depends on), I needed more recent versions of ROCm and GCC. These changes add GCC 13.2 and 6.2.0 to the frontier configuration. Does it make sense to add these?

**Comment by kwryankrattiger** [comment]
I am a bit surprised that those are required for the latest, I am not aware of anything that would force that. LLVM is locked to the Mesa version for OSMesa and OSPRay.

That aside, thanks for adding these! I don't think it hurts to make the available, especially if people want to use them :)

**Comment by kmorel** [comment]
I don't know if it has to do with the latest version or perhaps there was something weird about my configuration where the LLVM insisted on compiling itself with the AMD clang compiler (not GCC), and that cause the compile error. (Or maybe you had a patch that I don't.)

At any rate, I doubt I have access to merge this in. If you are comfortable with these additions, @kwryankrattiger, I'll need you to merge them in.

**Comment by kwryankrattiger** [comment]
I also do not have permission, @eugeneswalker is the guy :)

**Comment by eugeneswalker** [comment]
Thank you for updating this!

**Pull request merged**
